version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 1234
      POSTGRES_DB: job_board_production
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 1234
      RAILS_ENV: ${RAILS_ENV:-production}
      RAILS_MASTER_KEY: 56f06c8bb4a44714788846a88a570e64
    env_file:
      - .env.production

volumes:
  postgres_data:
  bundle_cache:
  node_modules: