services:
  web:
    image: smakthe/job-board-web:latest
    ports:
      - "3002:80"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - data:/rails/storage

volumes:
  data:
