services:
  web:
    build: .
    container_name: job_board
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
    volumes:
      - job_board_data:/rails/storage

volumes:
  job_board_data:
